import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import { Button } from "@/components/ui/button";
import { Home, ShoppingBag, LayoutList, Mails, User, ShoppingCart } from "lucide-react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="fixed left-10 top-20 gap-8">
          <Link href={"/"}>
            <div className="w-60 h-40 rounded-lg bg-fuchsia-700 mb-4">
            </div>
          </Link>
          <div className="flex flex-col gap-2">
            <Link href={"/"}><Button className="w-60 justify-start bg-gray-200 text-gray-700 hover:bg-fuchsia-200 hover:text-fuchsia-700"><Home className="mr-2 h-4 w-4" /> Home</Button></Link>
            <Link href={"/"}><Button className="w-60 justify-start bg-gray-200 text-gray-700 hover:bg-fuchsia-200 hover:text-fuchsia-700"><ShoppingBag className="mr-2 h-4 w-4" /> Shop</Button></Link>
            <Link href={"/"}><Button className="w-60 justify-start bg-gray-200 text-gray-700 hover:bg-fuchsia-200 hover:text-fuchsia-700"><LayoutList className="mr-2 h-4 w-4" /> About us</Button></Link>
            <Link href={"/"}><Button className="w-60 justify-start bg-gray-200 text-gray-700 hover:bg-fuchsia-200 hover:text-fuchsia-700"><Mails className="mr-2 h-4 w-4" /> Contact</Button></Link>
            <Link href={"/"}><Button className="w-60 justify-start bg-gray-200 text-gray-700 hover:bg-fuchsia-200 hover:text-fuchsia-700"><User className="mr-2 h-4 w-4" /> Account</Button></Link>
            <Link href={"/"}><Button className="w-60 justify-start bg-gray-200 text-gray-700 hover:bg-fuchsia-200 hover:text-fuchsia-700"><ShoppingCart className="mr-2 h-4 w-4" /> Cart</Button></Link>
          </div>
        </header>
        <div className="px-80 py-20">
          {children}
        </div>
      </body>
    </html>
  );
}
